dam/urls.py
from django.urls import path

from dam.views import dam_challenge, submit_challenge


app_name = 'dam'

urlpatterns = [
    path('dam/', dam_challenge, name='challenge'),
    path('dam/submit/', submit_challenge, name='submit_challenge'),
]

dam/views.py
import json
import time
import datetime
from base64 import b64decode


from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import render
from django.core.cache import cache
from django.views.decorators.http import require_GET, require_POST
from altcha import create_challenge, verify_solution


@require_GET
def dam_challenge(request):
    """Provide user an Altcha challenge to solve before allowing access."""
    challenge_expire_mins = getattr(settings, 'ALTCHA_CHALLENGE_EXPIRE_MINUTES', 2)
    challenge = create_challenge(
        expires=datetime.datetime.now() + datetime.timedelta(minutes=challenge_expire_mins),
        max_number=settings.ALTCHA_MAX_NUMBER,
        hmac_key=settings.ALTCHA_HMAC_KEY,
        # Use the params to add arbitrary values to the salt, potentially increasing security
        params=getattr(settings, 'ALTCHA_SALT_PARAMS', {}),
    )
    next_url = request.GET.get('next', '/')
    return render(
        request,
        'dam_challenge.html',
        {
            'challenge': challenge,
            'site_icon_url': getattr(settings, 'ALTCHA_SITE_ICON_URL', ''),
            'js_src_url': getattr(
                settings, 'ALTCHA_JS_URL', f'{settings.STATIC_URL}altcha/altcha.min.js'),
            'css_src_url': getattr(
                settings, 'ALTCHA_CSS_URL', f'{settings.STATIC_URL}dam/dam.css'),
            'altcha_message': getattr(settings,
                                      'ALTCHA_MESSAGE',
                                      'Gauging your humanity...This may take some seconds.'),
            'next_url': next_url,
            'original_referrer': request.session.get(f'referer{next_url}', ''),
            'help_text': getattr(settings,
                                 'ALTCHA_HELP_MESSAGE',
                                 ''),
        }
    )


@require_POST
def submit_challenge(request):
    """Attempt to validate Altcha challenge solution."""
    try:
        payload = json.loads(b64decode(request.POST.get('altcha')))
    except Exception:
        payload = {}
    ok, err = verify_solution(payload, settings.ALTCHA_HMAC_KEY, check_expires=True)
    # If the solution validates and hasn't already been seen, create/update their session dam
    # expiration, as well as saving the challenge in cache.
    if (isinstance(payload, dict) and ok
            and not cache.get(payload.get('challenge'))):
        challenge_expire_mins = getattr(settings, 'ALTCHA_CHALLENGE_EXPIRE_MINUTES', 2)
        auth_expire_mins = getattr(settings, 'ALTCHA_AUTH_EXPIRE_MINUTES', 480)
        cache.set(
            payload['challenge'],
            't',
            timeout=challenge_expire_mins*60)
        altcha_session_key = getattr(settings, 'ALTCHA_SESSION_KEY', 'altcha_verified')
        request.session[altcha_session_key] = time.time() + auth_expire_mins*60
        # Remove no longer needed data from session.
        next_url = request.POST.get('next', ['/'])
        try:
            del request.session[f'referer{next_url}']
        except KeyError:
            pass
        return JsonResponse({'success': True})
    # Otherwise, reject them.
    fail_msg = getattr(settings, 'ALTCHA_FAIL_MESSAGE', 'Challenge failed or no longer valid.')
    return JsonResponse({'error': fail_msg}, status=400)

dam/templates/dam_challenge.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;  charset=UTF-8" />
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DAM</title>
    <link rel="stylesheet" href="{{ css_src_url }}">
    <script async defer src="{{ js_src_url }}" type="module"></script>
</head>
<body>
    <div id="altcha-content">
        <h1><img src="{{ site_icon_url }}"> {{ request.get_host }}</h1>
        <h2>{{ altcha_message }}</h2>
        <div>
            <form id="altcha-submission">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next_url }}">
                <altcha-widget id="altcha"></altcha-widget>
            </form>
        </div>
        {% if help_text %}
            <h3>{{ help_text|safe }}</h3>
        {% endif %}
    </div>
    <script type="text/javascript">
        window.addEventListener("load", () => {
            document.querySelector("#altcha").configure({
                challenge: {
                    algorithm: "{{ challenge.algorithm }}",
                    challenge: "{{ challenge.challenge }}",
                    salt: "{{ challenge.salt }}",
                    signature: "{{ challenge.signature }}",
                    maxnumber: "{{ challenge.max_number }}",
                },
                auto: "onload",
                debug: false,
                delay: 0,
                hidefooter: true,
                hidelogo: false,
            });
        });
        document.querySelector("altcha-widget").addEventListener("statechange", async (e) => {
            await e.detail;
            if (e.detail.state === "verified") {
                const challengeData = new FormData(document.forms["altcha-submission"]);
                try {
                   const response = await fetch("{% url 'dam:submit_challenge' %}", {
                        method: "POST",
                        body: challengeData,
                    });
                    const result = await response.json();
                    if ("success" in result) {
                        if ("{{ original_referrer }}") {
                            window.history.replaceState({}, "" , "{{ original_referrer }}");
                        }
                        window.location.replace("{{ next_url }}");
                    } else {
                        document.getElementById('altcha-content').innerHTML = `${result.error} {{ help_text|safe }}`;
                    }
                } catch (error) {
                    document.getElementById('altcha-content').innerHTML = `${error} {{ help_text|safe }}`;
                    console.error("Challenge submission error:", error);
                }
            }
        });
    </script>
</body>
</html>

dam/templates/dam_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;  charset=UTF-8" />
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DAM</title>
    <!-- <link rel="stylesheet" href="/static/dam.css"> -->
    <script async defer src="{{ js_src_url }}" type="module"></script>
</head>
<body>
    <h1>Gauging your humanity...</h1>
    <h2>This may take some seconds.</h2>
    <form id="altcha-submission" action="{% url 'dam:dam_form' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next_url }}">
        {{ form }}
    </form>
    <script type="text/javascript">
        document.querySelector("altcha-widget").addEventListener("statechange", (ev) => {
            if (ev.detail.state === "verified") {
                setTimeout(() => {
                    document.forms["altcha-submission"].submit();
                }, 1000);
            }
        });
    </script>
</body>
</html>